title: Chris's Corner
description: >- # this means to ignore newlines until "baseurl:"
  Personal Blog
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://amoxyz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Amoxyz

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins:
  - jekyll-include-cache

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
